### ISSUE TITLE
Cleanup: Clean kubeconfig

### ISSUE THREAD

**Issue by anton-johansson** [amimof/kubernetes-the-right-way#16]
Would it be a good idea to clean up the `~/.kube/config` when running `cleanup.yml`?

```
$ kubectl config unset clusters.{{ cluster_name }}
$ kubectl config unset contexts.{{ cluster_name }}
$ kubectl config unset users.{{ cluster_name }}
```

We don't have the `cluster_name` variable in `cleanup.yml` though. :)

**Comment by anton-johansson** [comment]
Yeah, if you specify it. But I guess we can add the following to the top of `cleanup.yml`:

```yaml
- set_fact:
    cluster_hostname: "{{ cluster_hostname | default(groups['masters'][0]) }}"

- set_fact:
    cluster_name: "{{ cluster_name | default(cluster_hostname.split('.')[0] | default('kubernetes')) }}"
```

... to make sure the variable is set?
