### ISSUE TITLE
Pod networking

### ISSUE THREAD

**Issue by anton-johansson** [amimof/kubernetes-the-right-way#25]
I know pod networking isn't something that should be handled by this repository, but I have a minor question. I've just gotten into pod networking, I've previously worked with a single worker node, meaning that the bridge supplied by this repository has worked wonders.

This repository supplies a bridge using the subnet `10.19.0.0/16`.
This repository installs `kube-controller-manager` with the argument `--cluster-cidr=10.19.0.0/16`, which I believe is in charge of appointing IP addresses to each new pod.

I've now installed Flannel that should be used as an overlay network for proper pod networking. The configuration for it uses the subnet `10.244.0.0/16` (from the default in the flannel repository).

My question: How am I supposed to tell my cluster to use the Flannel subnet instead? One idea would be to have an Ansible parameter for this, but I'm kind of clueless here. Is that the right way to go? Or am I missing something? :)

**Comment by anton-johansson** [comment]
I think I've got this all wrong. Don't mind this for now, let me wrap my head around this a bit more.

**Comment by amimof** [comment]
Added `cluster_cidr` variable. Looks like changing the CIDR in runtime is harder than i thought. 
https://github.com/kubernetes/kubernetes/issues/50305

**Comment by anton-johansson** [comment]
I have some struggle setting the cluster CIDR alltogether. I've set it to `10.244.0.0/16` as I mentioned above, and the logs of `kube-controller-manager` looks correct:
```
Jan 08 09:42:12 k8s-master-01 kube-controller-manager[2178]: I0108 09:42:12.004863    2178 range_allocator.go:310] Set node k8s-worker-02 PodCIDR to 10.244.0.0/24
Jan 08 09:42:12 k8s-master-01 kube-controller-manager[2178]: I0108 09:42:12.059812    2178 range_allocator.go:310] Set node k8s-worker-01 PodCIDR to 10.244.2.0/24
Jan 08 09:42:12 k8s-master-01 kube-controller-manager[2178]: I0108 09:42:12.311693    2178 range_allocator.go:310] Set node k8s-worker-03 PodCIDR to 10.244.1.0/24
```

But when creating deployments, Pods still get IP addresses in the "old" CIDR, like `10.19.0.9`  and `10.19.0.13`.

I'll get the latest changes from master and see if it works better.

**Comment by amimof** [comment]
@anton-johansson 
Have a look in `/etc/cni/net.d/10-bridge.conf`:
```
{
  "cniVersion": "0.3.1",
  "name": "bridge",
  "type": "bridge",
  "bridge": "cnio0",
  "isGateway": true,
  "ipMasq": true,
  "ipam": {
    "type": "host-local",
    "ranges": [
      [{"subnet": "10.19.0.0/16"}]
    ],
    "routes": [{"dst": "0.0.0.0/0"}]
  }
}
```

**Comment by anton-johansson** [comment]
Ah, that is probably it. Should the subnet of the bridge be the same as the Flannel one? I think that'll happen with your latest changes, which I did not do. Let me give it a go.

**Comment by anton-johansson** [comment]
Actually, I'm gonna wait until #23 is done. :)

**Comment by anton-johansson** [comment]
```
Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "999fd02c43b32f1930384ec5abe15d0fa7177593868e1982bd47f9c29083f783": failed to set bridge addr: "cni0" already has an IP address different from 10.244.0.1/16
```

It does not seem to like it when both Flannel and the Bridge use the same subnet, which makes sense. Maybe the idea is to remove the Bridge in favor of Flannel?

**Comment by amimof** [comment]
Are you trying on a fresh install or have you changed the CIDR afterwards? Apparently that causes issues.

**Comment by anton-johansson** [comment]
I'm doing fresh installations now, to make sure I get things right.

Here's my Flannel configuration:
```yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        { 
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
```

... where `cni-conf.json` is moved to `/etc/cni/net.d/10-flannel.conflist` by an init container.

I think I'm missing something regarding how the bridge plays together with Flannel (or other overlay networks).
