### ISSUE TITLE
Metrics for containerd

### ISSUE THREAD

**Issue by anton-johansson** [amimof/kubernetes-the-right-way#47]
https://github.com/containerd/containerd/blob/8706a355dd603338d4a3026e66f6477fbdb18ef9/docs/ops.md

Looks like `containerd` can expose Prometheus metrics using this configuration snippet:
```toml
[metrics]
  # tcp address!
  address = "127.0.0.1:1234"
```

Can we get this into KTRW? By default, or optionally somehow? It would be nice to be able to see these metrics. Also, I can use this port to see if containerd is up and running (I'm experimenting with sequencial Ansible).
