### ISSUE TITLE
Downtime during upgrades

### ISSUE THREAD

**Issue by anton-johansson** [amimof/kubernetes-the-right-way#62]
Even though we've enabled some kind of HA solution with `serial_all=50%`, I still get some downtime during upgrades. I assume this is because when containerd is up again on node 1, we almost immediately take containerd down on node 2. If deployments only have two replicas (which is a common case), it makes sense that this deployment will have downtime.

What can we do in order to properly wait between nodes? One idea would be to actually ask the API server. We could check node status with `kubectl get node <node-name>`. Could we also check something like number of non-ready pods on a specific node? Maybe you actually have non-ready pods intentionally?

Another idea could be a configurable delay between nodes? Maybe that's sufficient? 

Does Ansible have a way of waiting for user input here? If so, that would be even better, so I can manually confirm that the node is back up at 100%.

**Comment by anton-johansson** [comment]
Here are an example from the [`pause` Ansible module](https://docs.ansible.com/ansible/latest/modules/pause_module.html):

```yaml
# Pause for 5 minutes to build app cache.
- pause:
    minutes: 5

# Pause until you can verify updates to an application were successful.
- pause:

# A helpful reminder of what to look out for post-update.
- pause:
    prompt: "Make sure org.foo.FooOverload exception is not present"

# Pause to get some sensitive input.
- pause:
    prompt: "Enter a secret"
    echo: no
```

**Comment by amimof** [comment]
I haven't been able to replicate the problem. I even tried with stopping containerd completely on two nodes. One running a nginx ingress controller, and the other a simple web app. I could still access the web app. However I did run into problems when restarting kubelet which seems to cause downtime. I think this is due to how networking is provisioned though kubelet's with the  services.

**Comment by anton-johansson** [comment]
Hmm, you're probably right. But it's probably not `kubelet`. `kube-proxy` is more likely, as that's the component handling the network routing.

Strange that you cannot reproduce though... How did you test your pods during the upgrade process?

**Comment by amimof** [comment]
That makes sense. I didn't do an upgrade, just took down containerd and kubelet. I'll do an upgrade and see what happens. Can you share any particular curl command to run during the upgrade? I would appreciate it.

**Comment by anton-johansson** [comment]
Aha. I had a cluster of two nodes. I had flannel, CoreDNS, NGINX Ingress controller and a simple [whoami](https://hub.docker.com/r/containous/whoami) service. Two replicas.

I had this command active while running the upgrade:
```shell
while true; do curl 'http://whoami.anton-johansson.local'; sleep 0.1; done
```

**Comment by anton-johansson** [comment]
Manifest for the whoami service:

```yaml
---
kind: Namespace
apiVersion: v1
metadata:
  name: whoami

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: whoami
  labels:
    app.kubernetes.io/name: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whoami
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: whoami
          image: containous/whoami:v1.0.1
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          args:
            - '-port'
            - '12345'

---
kind: Service
apiVersion: v1
metadata:
  name: whoami
  namespace: whoami
  labels:
    app.kubernetes.io/name: whoami
spec:
  selector:
    app.kubernetes.io/name: whoami
  ports:
    - port: 8080
      targetPort: 12345
      protocol: TCP

---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: whoami
  namespace: whoami
  labels:
    app.kubernetes.io/name: whoami
  annotations:
    kubernetes.io/ingress.class: external
spec:
  rules:
    - host: whoami.anton-johansson.local
      http:
        paths:
          - path: /
            backend:
              serviceName: whoami
              servicePort: 8080
```
